fict_chars/models.py
from enum import unique
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
import uuid
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import LoginManager, UserMixin
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
ma = Marshmallow()
login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    char = db.relationship('Char', backref='owner', lazy=True)

    def __init__(self, email, password, token = '', id = ''):
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.set_token(24)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def set_token(self, length):
        return secrets.token_hex(length)

class Char(db.Model):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(150))
    description = db.Column(db.String(200), nullable = True)
    bio = db.Column(db.String(250))
    physical_appearance = db.Column(db.String(150), nullable = True)
    universe = db.Column(db.String(100))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, name, description, bio, physical_appearance, universe, user_token, id = ''):
        self.id = self.set_id()
        self.name = name
        self.description = description
        self.bio = bio
        self.physical_appearance = physical_appearance
        self.universe = universe
        self.user_token = user_token

    def set_id(self):
        return (secrets.token_urlsafe())

class CharSchema(ma.Schema):
    class Meta:
        fields = ['id', 'name','description', 'bio', 'physical_appearance', 'universe']

char_schema = CharSchema()
chars_schema = CharSchema(many=True)

fict_chars/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms import validators
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired, Email

class UserLogInForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField()

fict_chars/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api
from flask_migrate import Migrate
from .models import db, login_manager, ma
from flask_cors import CORS

app = Flask(__name__)
app.config.from_object(Config)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

db.init_app(app)
ma.init_app(app)
login_manager.init_app(app)
login_manager.login_view = 'auth.signin' 

migrate = Migrate(app, db)

CORS(app)

fict_chars/api/routes.py
from operator import methodcaller
from flask import Blueprint, json, request, jsonify
from fict_chars.helpers import token_required
from fict_chars.models import Char, db, char_schema, chars_schema

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'some_value': 52, 'another_value': 'Coding Temple'}

@api.route('/chars', methods=['POST'])
@token_required
def create_char(current_user_token):
    name = request.json['name']
    description = request.json['description']
    bio = request.json['bio']
    physical_appearance = request.json['physical_appearance']
    universe = request.json['universe']
    token = current_user_token.token
    char = Char(name,description,bio,physical_appearance,universe,user_token = token)

    db.session.add(char)
    db.session.commit()
    response = char_schema.dump(char)
    return jsonify(response)

@api.route('/chars', methods = ['GET'])
@token_required
def get_chars(current_user_token):
    owner = current_user_token.token
    chars = Char.query.filter_by(user_token = owner).all()
    response = chars_schema.dump(chars)
    return jsonify(response)

@api.route('/chars/<id>', methods = ['GET'])
@token_required
def get_char(current_user_token, id):
    char = Char.query.get(id)
    response = char_schema.dump(char)
    return jsonify(response)

@api.route('/chars/<id>', methods = ['POST', 'PUT'])
@token_required
def update_char(current_user_token, id):
    char = Char.query.get(id)
    print(char)
    if char:
        char.name = request.json['name']
        char.description = request.json['description']
        char.bio = request.json['bio']
        char.physical_appearance = request.json['physical_appearance']
        char.universe = request.json['universe']
        char.user_token = current_user_token.token
        db.session.commit()

        response = char_schema.dump(char)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That character does not exist.'})

@api.route('/chars/<id>', methods = ['DELETE'])
@token_required
def delete_char(current_user_token, id):
    char = Char.query.get(id)
    if char:
        db.session.delete(char)
        db.session.commit()
        response = char_schema.dump(char)
        return jsonify({'Success': f'Character ID #{char.id} has been deleted'})
    else: 
        return jsonify({'Error': 'That character does not exist.'})

fict_chars/authentication/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from fict_chars.forms import UserLogInForm
from fict_chars.models import User, db, check_password_hash
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLogInForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        flash(f'You have successfully registered an account and logged in under {email}', 'user-created')
        return redirect(url_for('site.home'))
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLogInForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email,password)
        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You were successfully logged in.', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have successfully logged out.', 'auth-success')
    return redirect(url_for('site.home'))

fict_chars/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')
    

fict_chars/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Fictional Characters Database</title>
</head>
<body>
    <nav class="ct-nav">
        <div>
            <a href="{{ url_for('site.home') }}">
                <img src="../static/images/vader-logo.png" id="vader-logo" alt="Logo">
            </a>
        </div>
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a>
                <a href="">
                    <li>Database</li>
                </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    <a href="{{url_for('auth.logout') }}">
                        <li>Log Out</li>
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                {% endif %}    
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>